### ISSUE TITLE
No issue just a question

### ISSUE THREAD

**Issue by Heclalava** [im-sm/Pi-hole-Torrent-Blocklist#1]
I was curious how do you source your trackers and torrent websites to add to your lists?

**Comment by im-sm** [comment]
These are the sources. 

https://blocklistproject.github.io/Lists/alt-version/torrent-nl.txt
https://raw.githubusercontent.com/nextdns/piracy-blocklists/master/torrent-websites
https://trackerslist.com/all.txt
https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
https://raw.githubusercontent.com/nextdns/piracy-blocklists/master/torrent-trackers

Have a nice day. ✨
