### ISSUE TITLE
New pirate bay mirror's that should be added

### ISSUE THREAD

**Issue by FuckFiveM69** [im-sm/Pi-hole-Torrent-Blocklist#3]
These PirateBay Mirror's are not added to the list and unblocked

tpb24.ukpass.co
pirate-proxy.club
ukpass.fun
uk-pirate.com
pirate-proxy.fun
piratepiratebay.com
uk-pirate-bay.com
piraat.xyz
piratebayorg.net
proxifiedpiratebay.org
unlockedpiratebay.com
piratebayproxy.rocks
pirateproxy.network
pirateproxy.best
pirateproxy.digital
pirateproxy.quest
mirrorbay.top
tpb24.ukpass.co
thepb.cyou
tpb24.ukpass.co
piratebayproxy.live
5mins.shop
piratesbay.sbs

**Comment by im-sm** [comment]
Updated. Thank you.
